<?php

namespace Noback\PHPUnitTestServiceContainer\PHPUnit;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use Noback\PHPUnitTestServiceContainer\ServiceProvider\DoctrineDbalServiceProvider;

trait TestCaseWithDoctrineDbalConnection
{
    use TestCaseWithServiceContainer;

    /**
     * Return a Schema object. The DoctrineDbalServiceProvider will execute the SQL statements generated by it to
     * prepare the database for your tests.
     *
     * @return Schema
     */
    abstract protected function createSchema(): Schema;

    protected function getServiceProviders(): array
    {
        $schema = $this->createSchema();

        return [
            new DoctrineDbalServiceProvider($schema)
        ];
    }

    /**
     * Get the Doctrine DBAL connection
     *
     * @return Connection
     */
    protected function getConnection(): Connection
    {
        return $this->container['doctrine_dbal.connection'];
    }
}
