<?php

namespace Noback\PHPUnitTestServiceContainer\PHPUnit;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use Noback\PHPUnitTestServiceContainer\ServiceProvider\DoctrineDbalServiceProvider;

abstract class AbstractTestCaseWithDoctrineDbalConnection extends AbstractTestCaseWithServiceContainer
{
    /**
     * Return a Schema object. The DoctrineDbalServiceProvider will execute the SQL statements generated by it to
     * prepare the database for your tests.
     *
     * @return Schema
     */
    abstract protected function createSchema();

    protected function getServiceProviders()
    {
        $schema = $this->createSchema();

        return array(
            new DoctrineDbalServiceProvider($schema)
        );
    }

    /**
     * Get the Doctrine DBAL connection
     *
     * @return Connection
     */
    protected function getConnection()
    {
        return $this->container['doctrine_dbal.connection'];
    }
}
